; Listing generated by Microsoft (R) Optimizing Compiler Version 19.12.25835.0 

; Generated by VC++ for Common Language Runtime
.file "C:\Users\ryout\AppData\Local\Temp\.NETFramework,Version=v4.5.AssemblyAttributes.cpp"
